serviceMonitor:
  selfMonitor:
    enabled: true

  targets:
   - name: student-api                    # Human readable URL that will appear in Prometheus / AlertManager
     url: http://student-api:5000/api/v1/healthcheck  # The URL that blackbox will scrape
     hostname: student-api         # HTTP probes can accept an additional `hostname` parameter that will set `Host` header and TLS SNI
     labels: {}                       # Map of labels for ServiceMonitor. Overrides value set in `defaults`
     interval: 60s                    # Scraping interval. Overrides value set in `defaults`
     scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
     module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`
     additionalMetricsRelabels: {}    # Map of metric labels and values to add
     additionalRelabeling: []         # List of metric relabeling actions to run


commonLabels:
  release: grafana

config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        follow_redirects: true
        preferred_ip_protocol: "ip4"