replicaCount: 1
image:
  repository: pasivinay/student-api
  tag: "1.0.1"
  pullPolicy: Always
database:
  secretName: db-secrets
service:
  type: NodePort
  port: 5000
deployment:
  nodeSelector:
    type: application

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 800Mi