apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      nodeSelector:
        type: database
      containers:
        - name: mysql
          image: mysql:8.0-oracle
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-config
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: root-password
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: student-api
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None
