version: "3.3"
services:
  db:
    image: mysql:8.0-oracle
    container_name: student-db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  api1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-api1
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8001:5000"

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-api2
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8002:5000"
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2