{
 "title": "Loki Logs",
 "tags": [ "one2n-sre-bootcamp-dashboards" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values({namespace=\"$namespace\"}, deployment)"
   },
   {
    "name": "app",
    "label": "App",
    "query": "label_values({namespace=\"$namespace\", deployment=\"$deployment\"}, app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Logs volume",
   "type": "timeseries",
   "description": "Log volume over time with error highlighting",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", deployment=\"$deployment\", app=~\"$app\"} [1m]))",
     "legendFormat": "logs"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", deployment=\"$deployment\", app=~\"$app\"} |~ \"(?i)error\" [1m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", deployment=\"$deployment\", app=~\"$app\"} |~ \"(?i)error\""
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", deployment=\"$deployment\", app=~\"$app\"} | logfmt"
    }
   ]
  }
 ]
}