apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.student-api.namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.vault.namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.external-secrets.namespace }}