apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  namespace: {{ .Values.clusterSecretStore.namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.clusterSecretStore.vault.server | quote }}
      path: {{ .Values.clusterSecretStore.vault.path | quote }}
      version: {{ .Values.clusterSecretStore.vault.version | quote }}
      auth:
        tokenSecretRef:
          name: {{ .Values.clusterSecretStore.vault.auth.tokenSecretRef.name | quote }}
          key: {{ .Values.clusterSecretStore.vault.auth.tokenSecretRef.key | quote }}
          namespace: {{ .Values.clusterSecretStore.vault.auth.tokenSecretRef.namespace | quote }}