apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: student-api-cluster-secretstore
  namespace: student-api
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"  # Change this to your Vault address
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: external-secrets  # Adjust this based on where the token secret is stored
