apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secrets
  namespace: student-api
spec:
  secretStoreRef:
    name: student-api-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: db-secrets
  data:
    - secretKey: username
      remoteRef:
        key: secret/db-creds
        property: username
    - secretKey: password
      remoteRef:
        key: secret/db-creds
        property: password
    - secretKey: db-url
      remoteRef:
        key: secret/db-creds
        property: db-url
    - secretKey: root-password
      remoteRef:
        key: secret/db-creds
        property: root-password
    - secretKey: database
      remoteRef:
        key: secret/db-creds
        property: database